### ISSUE TITLE
Struct contents reference from a non-struct array object.

### ISSUE THREAD

**Issue by aanexplus** [wspr/bvh-matlab#1]
Hi,
I tried your code (loadbvh.m) with the data you provided and it worked just fine. Meanwhile, I tried the code with my data and I got "Struct contents reference from a non-struct array object." error. I noticed your file header length is 114 while mine is 129. How can this error be fixed? 

Thanks
[aaa.zip](https://github.com/wspr/bvh-matlab/files/1627101/aaa.zip)

**Comment by wspr** [comment]
Thanks for the feedback. The problem in my code here is that your file is tab-delimited, while the files I had for testing were space delimited.

In the short term you can replace the line

    rawdata = importdata(fname,' ',Nheaderlines);

with

    rawdata = importdata(fname,'\t',Nheaderlines);

I've pushed an update which addresses this with

    loadbvh('aaa.bvh','delim','\t')

**Comment by aanexplus** [comment]
Thanks for the swift response. It works like magic. I will send an email to your gmail address. I will appreciate if you can respond. You can close this issue.

Best Regards.
