### ISSUE TITLE
function plot_coord()

### ISSUE THREAD

**Issue by liyuebit** [wspr/bvh-matlab#2]
Is plot_coord() the function in Matlab itself?
When I run optitrack.m, there is an error Undefined function or variable about  plot_coord(). 
How can I fix it? 
Hope your reply. 
Thank you.

**Comment by wspr** [comment]
Apologies. You can simply remove that line of code.

**Comment by wspr** [comment]
I've now updated the example without this function.

**Comment by liyuebit** [comment]
OK，Thank you.
