### ISSUE TITLE
3d points to bvh?

### ISSUE THREAD

**Issue by chenloveheimei** [wspr/bvh-matlab#3]
hello,My name is Long.
I saw your program which transform the rotation into 3d Points.
Question:
how can I transform 3d Points into rotations for bvh.file?
thx.

**Comment by wspr** [comment]
Sorry, that's not something this tool can do. You might like to look into the book "Introduction to Robotics" by Craig: <https://www.pearson.com/us/higher-education/program/Craig-Introduction-to-Robotics-Mechanics-and-Control-4th-Edition/PGM91709.html>
